### ISSUE TITLE
REQUEST: Data Dictionary

### ISSUE THREAD

**Issue by MattyinAK** [codeforanchorage/Anchorage-Property-Tax-Data#1]
Is there a data dictionary available for the tax data?  I've started parsing the file - but there are no column headers (in the .ascii file) and some of them are not straightforward enough to figure out.

**Comment by hansthompson** [comment]
I know there is one.   I can't open the compressed folders right now but check there if you haven't yet.  Otherwise I will dig it up. 😅

**Comment by hansthompson** [comment]
IF you look in Anchorage-Property-Tax-Data.rar  there is a file Public Tape data description.XLS.  This is the best description that was available to us.  

Also, if you look at;
 https://github.com/codeforanchorage/moa_property_tax_geojson/blob/master/main.py
you can see how it was used to parse the fields with python.

**Comment by MattyinAK** [comment]
Thanks!
